## Introducción a Pandas

**Pandas** es una librería de Python diseñada para trabajar con **datos estructurados**, como tablas y series de datos.

Sus principales estructuras son:

* **Series**: una secuencia de datos asociada a un índice.
* **DataFrame**: una tabla formada por filas y columnas.

Pandas permite cargar, explorar, seleccionar, filtrar y analizar datos de forma sencilla. Además, se integra fácilmente con otras librerías como **NumPy** y **Matplotlib**.

In [2]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [3]:
pip install pandas numpy xarray matplotlib

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting xarray
  Downloading xarray-2026.7.0-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (80 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: packaging>=24.2 in /home/codespace/.local/lib/python3.14/site-packages (from xarray) (26.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.64.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (123 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.2 kB)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 59.4 MB/s  0:00:00
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 52.0 MB/s  0:00:006m0:00:01
Downloading xarray-2026.7.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 38.9 MB/s  0:00:00
Downloading matplotlib-3.11.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 50.7 MB/s  0:00:006m0:00:01
Downloading contourpy-1.3.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (363 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.64.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 54.9 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 31.8 MB/s  0:00:00
Downloading pillow-12.3.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 56.1 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, xarray, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [matplotlib]0 [matplotlib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.64.0 kiwisolver-1.5.1 matplotlib-3.11.1 numpy-2.5.3 pandas-3.0.5 pillow-12.3.0 pyparsing-3.3.2 xarray-2026.7.0
Note: you may need to restart the kernel to use updated packages.

Una Series de Pandas es una estructura que representa una única columna de datos junto con un índice.

In [ ]:
#### Series

temperatura = pd.Series([20, 21, 23, 22, 19])

print(temperatura)

0    20
1    21
2    23
3    22
4    19
dtype: int64

In [ ]:
print(temperatura.mean())
print(temperatura.std())

21.0
1.5811388300841898

¿Qué es un DataFrame?

Un DataFrame es la estructura de datos principal de Pandas para trabajar con datos organizados en forma de tabla, con filas y columnas.

Cada columna de un DataFrame es una Series, y todas las columnas comparten el mismo índice.

In [ ]:
df = pd.DataFrame({
    "temperatura": [20, 21, 23, 22, 19],
    "humedad": [70, 65, 60, 62, 75]
})

print(df)

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

In [ ]:
data = {
    "temperatura": [20, 21, 23, 22, 19],
    "humedad": [70, 65, 60, 62, 75]
}

df = pd.DataFrame(data)

print(df)

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

Algunas herramientas útiles para investigar un dataframe:

In [ ]:
df.head() #### muestra las primeras filas del DataFrame

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

In [ ]:
df.shape  #### muestra el número de filas y columnas del DataFrame

(6, 2)

In [ ]:
df.columns #### muestra los nombres de las columnas del DataFrame

Index(['temperatura', 'humedad'], dtype='str')

In [ ]:
df["temperatura"] ### muestra la columna "temperatura" del DataFrame, recupera el objeto Series correspondiente a esa columna

0    20
1    21
2    22
3    23
4    24
5    25
Name: temperatura, dtype: int64

Aqui os dejo como unir dos dataframes diferentes, (tienen que compartir indice, si no necesitareis mas tratamiento), esto es util en el proceso de recopilación de datos

In [ ]:
np.random.seed(42)

temperatura = np.random.normal(20, 3, 100)
humedad = np.random.normal(60, 10, 100)

df = pd.DataFrame({
    "temperatura": temperatura,
    "humedad": humedad
})

In [ ]:
df1 = pd.DataFrame({
    "temperatura": [20, 21, 22],
    "humedad": [60, 65, 70]
})

df2 = pd.DataFrame({
    "temperatura": [23, 24, 25],
    "humedad": [68, 64, 61]
})

In [ ]:
df = pd.concat([df1, df2])

print(df)

   temperatura  humedad
0           20       60
1           21       65
2           22       70
0           23       68
1           24       64
2           25       61

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df

   temperatura  humedad
0           20       60
1           21       65
2           22       70
3           23       68
4           24       64
5           25       61