## Introducción a Pandas

**Pandas** es una librería de Python diseñada para trabajar con **datos estructurados**, como tablas y series de datos.

Sus principales estructuras son:

* **Series**: una secuencia de datos asociada a un índice.
* **DataFrame**: una tabla formada por filas y columnas.

Pandas permite cargar, explorar, seleccionar, filtrar y analizar datos de forma sencilla. Además, se integra fácilmente con otras librerías como **NumPy** y **Matplotlib**.

In [3]:
import pandas as pd
import numpy as np

Una Series de Pandas es una estructura que representa una única columna de datos junto con un índice.

In [4]:
#### Series

temperatura = pd.Series([20, 21, 23, 22, 19])

print(temperatura)

0    20
1    21
2    23
3    22
4    19
dtype: int64

In [5]:
print(temperatura.mean())
print(temperatura.std())

21.0
1.5811388300841898

¿Qué es un DataFrame?

Un DataFrame es la estructura de datos principal de Pandas para trabajar con datos organizados en forma de tabla, con filas y columnas.

Cada columna de un DataFrame es una Series, y todas las columnas comparten el mismo índice.

In [6]:
df = pd.DataFrame({
    "temperatura": [20, 21, 23, 22, 19],
    "humedad": [70, 65, 60, 62, 75]
})

print(df)

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

In [7]:
data = {
    "temperatura": [20, 21, 23, 22, 19],
    "humedad": [70, 65, 60, 62, 75]
}

df = pd.DataFrame(data)

print(df)

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

Algunas herramientas útiles para investigar un dataframe:

In [8]:
df.head() #### muestra las primeras filas del DataFrame

   temperatura  humedad
0           20       70
1           21       65
2           23       60
3           22       62
4           19       75

In [17]:
df.shape  #### muestra el número de filas y columnas del DataFrame

(6, 2)

In [18]:
df.columns #### muestra los nombres de las columnas del DataFrame

Index(['temperatura', 'humedad'], dtype='str')

In [20]:
df["temperatura"] ### muestra la columna "temperatura" del DataFrame, recupera el objeto Series correspondiente a esa columna

0    20
1    21
2    22
3    23
4    24
5    25
Name: temperatura, dtype: int64

Aqui os dejo como unir dos dataframes diferentes, (tienen que compartir indice, si no necesitareis mas tratamiento), esto es util en el proceso de recopilación de datos

In [12]:
np.random.seed(42)

temperatura = np.random.normal(20, 3, 100)
humedad = np.random.normal(60, 10, 100)

df = pd.DataFrame({
    "temperatura": temperatura,
    "humedad": humedad
})

In [13]:
df1 = pd.DataFrame({
    "temperatura": [20, 21, 22],
    "humedad": [60, 65, 70]
})

df2 = pd.DataFrame({
    "temperatura": [23, 24, 25],
    "humedad": [68, 64, 61]
})

In [14]:
df = pd.concat([df1, df2])

print(df)

   temperatura  humedad
0           20       60
1           21       65
2           22       70
0           23       68
1           24       64
2           25       61

In [15]:
df = pd.concat([df1, df2], ignore_index=True)

In [16]:
df

   temperatura  humedad
0           20       60
1           21       65
2           22       70
3           23       68
4           24       64
5           25       61