# 📊 Introducción al análisis de datos con Python

El objetivo de este notebook es servir como un **repositorio de ejemplos y ejercicios
para trabajar con datos tabulares**. Para ello, utilizaremos principalmente la librería
**pandas**.

---

Cuando trabajamos con una librería de Python, primero debemos **importarla** para poder
utilizar sus funciones.

Algunas librerías forman parte de la distribución estándar de Python, mientras que
otras han sido desarrolladas por terceros y deben instalarse previamente en el entorno
de trabajo.

> 💡 En muchos entornos educativos, como **Google Colab** o algunas instalaciones de
> **Jupyter**, las librerías más habituales ya están instaladas.

Una **librería** es un conjunto de código desarrollado para proporcionar funciones y
herramientas que facilitan la realización de determinadas tareas.

In [5]:
import pandas as pd

In [6]:
#### Podemos cargar datos de un excel o de un csv

path = '/lustre/geocean/WORK/users/alonsoap/personal/dodencia/AnaliticaDeDatos/datos/clases/clase_1_analisis_exploratorio_de_datos/Concrete_Data.xls' # Cuando quiero abrir un archivo, le tengo que decir al ordenador donde está
pd.read_excel(path)

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [7]:
#### Esto nos permite abrir un archivo, tengo que guardarlo en una variable/objeto para poder acceder a el y trabajar con los datos
concrete_data = pd.read_excel(path)

In [8]:
concrete_data

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [9]:
#### Los datos se dividen en columnas y filas. Las columnas son nuestras variables y las filas el valor que toman. 
#### La estructura de tabla de pandas se llama DataFrame. El tamaño de un dataframe se puede ver así. En este caso tenemos 9 columnas y 1030 filas

concrete_data.shape

(1030, 9)

In [10]:
#### Hay muchas formas de acceder a los datos. Familirizaros con algunas y ya ireis ampliando. Por ejemplo para acceder a una columna:
concrete_data['Concrete compressive strength(MPa, megapascals) ']

0       79.986111
1       61.887366
2       40.269535
3       41.052780
4       44.296075
          ...
1025    44.284354
1026    31.178794
1027    23.696601
1028    32.768036
1029    32.401235
Name: Concrete compressive strength(MPa, megapascals) , Length: 1030, dtype: float64

In [11]:
#### Tambien le podemos cambiar el nombre a una columna para que sea mas manejable
concrete_data = concrete_data.rename(columns={'Concrete compressive strength(MPa, megapascals) ':'compresive_strenght'})

In [12]:
concrete_data

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [13]:
#### La primera columna es el indice, si los datos no tienen indices, se ordenan con un valor numerico empezando por cero. Podemos acceder a una fila por su posicion o por el valor del indice. 
concrete_data.iloc[0] #### Por posicion

Cement (component 1)(kg in a m^3 mixture)                 540.000000
Blast Furnace Slag (component 2)(kg in a m^3 mixture)       0.000000
Fly Ash (component 3)(kg in a m^3 mixture)                  0.000000
Water  (component 4)(kg in a m^3 mixture)                 162.000000
Superplasticizer (component 5)(kg in a m^3 mixture)         2.500000
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     1040.000000
Fine Aggregate (component 7)(kg in a m^3 mixture)         676.000000
Age (day)                                                  28.000000
compresive_strenght                                        79.986111
Name: 0, dtype: float64

In [14]:
concrete_data.loc[0] #### Por el valor del indice.

Cement (component 1)(kg in a m^3 mixture)                 540.000000
Blast Furnace Slag (component 2)(kg in a m^3 mixture)       0.000000
Fly Ash (component 3)(kg in a m^3 mixture)                  0.000000
Water  (component 4)(kg in a m^3 mixture)                 162.000000
Superplasticizer (component 5)(kg in a m^3 mixture)         2.500000
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     1040.000000
Fine Aggregate (component 7)(kg in a m^3 mixture)         676.000000
Age (day)                                                  28.000000
compresive_strenght                                        79.986111
Name: 0, dtype: float64

In [15]:
#### En este caso coinciden. Un caso muy tipico es que el indice sean fechas. Voy a crear un vector de fechas de la logitud del dataframe y ponerselo como indice. 

concrete_data["Date"] = pd.date_range(
    start="2000-01-01",
    periods=len(concrete_data),
    freq="D"
)
concrete_data = concrete_data.set_index('Date')

In [16]:
concrete_data

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
Date,,,,,,,,,
2000-01-01,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
2000-01-02,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2000-01-03,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
2000-01-04,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
2000-01-05,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
2002-10-22,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
2002-10-23,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
2002-10-24,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
2002-10-25,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
2002-10-26,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [17]:
#### Ahora iloc sigue funcionado por posicion con 0, pero loc funciona con el valor del indice, que en este caso es una fecha.

In [18]:
concrete_data.iloc[0]

Cement (component 1)(kg in a m^3 mixture)                 540.000000
Blast Furnace Slag (component 2)(kg in a m^3 mixture)       0.000000
Fly Ash (component 3)(kg in a m^3 mixture)                  0.000000
Water  (component 4)(kg in a m^3 mixture)                 162.000000
Superplasticizer (component 5)(kg in a m^3 mixture)         2.500000
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     1040.000000
Fine Aggregate (component 7)(kg in a m^3 mixture)         676.000000
Age (day)                                                  28.000000
compresive_strenght                                        79.986111
Name: 2000-01-01 00:00:00, dtype: float64

In [19]:
concrete_data.loc['2000-01-01']

Cement (component 1)(kg in a m^3 mixture)                 540.000000
Blast Furnace Slag (component 2)(kg in a m^3 mixture)       0.000000
Fly Ash (component 3)(kg in a m^3 mixture)                  0.000000
Water  (component 4)(kg in a m^3 mixture)                 162.000000
Superplasticizer (component 5)(kg in a m^3 mixture)         2.500000
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     1040.000000
Fine Aggregate (component 7)(kg in a m^3 mixture)         676.000000
Age (day)                                                  28.000000
compresive_strenght                                        79.986111
Name: 2000-01-01 00:00:00, dtype: float64

In [20]:
concrete_data.loc[0] #### Ahora da error

KeyError: 0

In [21]:
#### Algunos metodos muy utiles para explorar los datos
#### .head() nos muestra las primeras 5 filas (o el numero que especifiquemos)
concrete_data.head(3)

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
Date,,,,,,,,,
2000-01-01,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
2000-01-02,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2000-01-03,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535

In [22]:
#### .tail() es parecido a head() pero muestra las últimas filas
concrete_data.tail()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
Date,,,,,,,,,
2002-10-22,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
2002-10-23,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
2002-10-24,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
2002-10-25,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
2002-10-26,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [23]:
#### .info() nos da información sobre el dataframe: tipos de datos, número de no-nulos, memoria usada, etc.
concrete_data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1030 entries, 2000-01-01 to 2002-10-26
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Cement (component 1)(kg in a m^3 mixture)              1030 non-null   float64
 1   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  1030 non-null   float64
 2   Fly Ash (component 3)(kg in a m^3 mixture)             1030 non-null   float64
 3   Water  (component 4)(kg in a m^3 mixture)              1030 non-null   float64
 4   Superplasticizer (component 5)(kg in a m^3 mixture)    1030 non-null   float64
 5   Coarse Aggregate  (component 6)(kg in a m^3 mixture)   1030 non-null   float64
 6   Fine Aggregate (component 7)(kg in a m^3 mixture)      1030 non-null   float64
 7   Age (day)                                              1030 non-null   int64
 8   compresive_strenght                                    1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 112.8 KB

In [24]:
#### .describe() nos da estadísticas descriptivas (media, std, min, max, percentiles, etc.) de las columnas numéricas
concrete_data.describe()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.165631,73.895485,54.187136,181.566359,6.203112,972.918592,773.578883,45.662136,35.817836
std,104.507142,86.279104,63.996469,21.355567,5.973492,77.753818,80.175427,63.169912,16.705679
min,102.000000,0.000000,0.000000,121.750000,0.000000,801.000000,594.000000,1.000000,2.331808
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.707115
50%,272.900000,22.000000,0.000000,185.000000,6.350000,968.000000,779.510000,28.000000,34.442774
75%,350.000000,142.950000,118.270000,192.000000,10.160000,1029.400000,824.000000,56.000000,46.136287
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.599225

In [25]:
## Sección 2: Seleccionar y Filtrar Datos

#### Puedes seleccionar una columna de varias formas:
cement = concrete_data['Cement (component 1)(kg in a m^3 mixture)']
print(type(cement))  # Una columna es una Series
print(cement.head())

<class 'pandas.Series'>
Date
2000-01-01    540.0
2000-01-02    540.0
2000-01-03    332.5
2000-01-04    332.5
2000-01-05    198.6
Name: Cement (component 1)(kg in a m^3 mixture), dtype: float64

In [26]:
#### Puedes seleccionar varias columnas a la vez usando una lista
selected_cols = concrete_data[['Cement (component 1)(kg in a m^3 mixture)', 'compresive_strenght']]
selected_cols.head()

            Cement (component 1)(kg in a m^3 mixture)  compresive_strenght
Date
2000-01-01                                      540.0            79.986111
2000-01-02                                      540.0            61.887366
2000-01-03                                      332.5            40.269535
2000-01-04                                      332.5            41.052780
2000-01-05                                      198.6            44.296075

In [27]:
#### Filtrar filas según una condición (WHERE en SQL)
#### Por ejemplo, solo las filas donde la resistencia del concreto es mayor a 40
strength_col = 'compresive_strenght'
strong_concrete = concrete_data[concrete_data[strength_col] > 40]
print(f"Número de muestras con resistencia > 40: {len(strong_concrete)}")
print(f"De un total de: {len(concrete_data)}")
strong_concrete.head()

Número de muestras con resistencia > 40: 379
De un total de: 1030

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
Date,,,,,,,,,
2000-01-01,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
2000-01-02,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2000-01-03,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
2000-01-04,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
2000-01-05,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [28]:
#### Puedes combinar múltiples condiciones con & (AND) y | (OR)
#### Por ejemplo: resistencia entre 30 y 40
strength_col = 'compresive_strenght'
medium_concrete = concrete_data[(concrete_data[strength_col] > 30) & (concrete_data[strength_col] < 40)]
print(f"Muestras con resistencia entre 30 y 40: {len(medium_concrete)}")
medium_concrete.head()

Muestras con resistencia entre 30 y 40: 253

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),compresive_strenght
Date,,,,,,,,,
2000-01-08,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.447770
2000-01-10,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.289790
2000-01-11,198.6,132.4,0.0,192.0,0.0,978.4,825.5,90,38.074244
2000-01-17,139.6,209.4,0.0,192.0,0.0,1047.0,806.9,90,39.358048
2000-01-29,427.5,47.5,0.0,228.0,0.0,932.0,594.0,28,37.427515

In [29]:
## Sección 3: Operaciones Estadísticas y Cálculos

#### Calcular estadísticas sobre una columna
cement_col = concrete_data['Cement (component 1)(kg in a m^3 mixture)']

print(f"Media: {cement_col.mean():.2f}")
print(f"Mediana: {cement_col.median():.2f}")
print(f"Desviación estándar: {cement_col.std():.2f}")
print(f"Mínimo: {cement_col.min():.2f}")
print(f"Máximo: {cement_col.max():.2f}")
print(f"Suma: {cement_col.sum():.2f}")

Media: 281.17
Mediana: 272.90
Desviación estándar: 104.51
Mínimo: 102.00
Máximo: 540.00
Suma: 289600.60

In [30]:
#### Crear una nueva columna a partir de operaciones
#### Por ejemplo, normalizamos la resistencia (restar media y dividir por desv. est.)
strength_col = 'compresive_strenght'
concrete_data['strength_normalized'] = (concrete_data[strength_col] - concrete_data[strength_col].mean()) / concrete_data[strength_col].std()

concrete_data[[strength_col, 'strength_normalized']].head()

            compresive_strenght  strength_normalized
Date
2000-01-01            79.986111             2.643908
2000-01-02            61.887366             1.560519
2000-01-03            40.269535             0.266478
2000-01-04            41.052780             0.313363
2000-01-05            44.296075             0.507506

In [32]:
#### Ordenar (sort) los datos por una columna
sorted_by_strength = concrete_data.sort_values('compresive_strenght', ascending=False)
print("Top 5 muestras con mayor resistencia:")
sorted_by_strength[['Cement (component 1)(kg in a m^3 mixture)', 'compresive_strenght']].head()

Top 5 muestras con mayor resistencia:

            Cement (component 1)(kg in a m^3 mixture)  compresive_strenght
Date
2000-06-30                                      389.9            82.599225
2001-01-16                                      315.0            81.751169
2000-06-02                                      323.7            80.199848
2000-01-01                                      540.0            79.986111
2000-06-08                                      389.9            79.400056

In [33]:
## Sección 4: Agrupaciones con GroupBy

#### Crear categorías de resistencia para demostrar groupby
def categorize_strength(value):
    if value < 20:
        return 'Baja'
    elif value < 40:
        return 'Media'
    else:
        return 'Alta'

concrete_data['strength_category'] = concrete_data['compresive_strenght'].apply(categorize_strength)

#### Contar cuantas muestras hay en cada categoría
print("Distribución de categorías:")
concrete_data['strength_category'].value_counts()

Distribución de categorías:

strength_category
Media    454
Alta     379
Baja     197
Name: count, dtype: int64

In [34]:
#### Agrupar por categoría y calcular estadísticas
grouped = concrete_data.groupby('strength_category')['Cement (component 1)(kg in a m^3 mixture)'].agg(['mean', 'std', 'count'])
print("Estadísticas de Cemento por categoría de resistencia:")
grouped

Estadísticas de Cemento por categoría de resistencia:

                         mean         std  count
strength_category
Alta               338.380369  103.766700    379
Baja               216.801675   72.528884    197
Media              261.331520   92.808992    454

In [35]:
## Sección 5: Manejo de Valores Faltantes (Missing Values)

#### Ver si hay valores nulos/faltantes en nuestros datos
print("Valores faltantes por columna:")
concrete_data.isnull().sum()

# También podemos verlo como porcentaje
print("\nPorcentaje de valores faltantes:")
(concrete_data.isnull().sum() / len(concrete_data) * 100).round(2)

Valores faltantes por columna:

Porcentaje de valores faltantes:

Cement (component 1)(kg in a m^3 mixture)                0.0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0.0
Fly Ash (component 3)(kg in a m^3 mixture)               0.0
Water  (component 4)(kg in a m^3 mixture)                0.0
Superplasticizer (component 5)(kg in a m^3 mixture)      0.0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0.0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0.0
Age (day)                                                0.0
compresive_strenght                                      0.0
strength_normalized                                      0.0
strength_category                                        0.0
dtype: float64

In [36]:
#### Formas de tratar los valores faltantes:

# 1. Eliminar filas con valores nulos
df_without_nulls = concrete_data.dropna()
print(f"Filas originales: {len(concrete_data)}")
print(f"Filas sin nulos: {len(df_without_nulls)}")

# 2. Rellenar valores nulos con un valor específico (ej: media)
# df_filled = concrete_data.fillna(concrete_data.mean())

# 3. Rellenar con el valor anterior o siguiente (útil para series temporales)
# df_filled = concrete_data.fillna(method='ffill')  # forward fill
# df_filled = concrete_data.fillna(method='bfill')  # backward fill

Filas originales: 1030
Filas sin nulos: 1030

In [37]:
## Sección 6: Guardar y Exportar Datos

#### Puedes guardar tu dataframe procesado en diferentes formatos:

# 1. Guardar como CSV
# concrete_data.to_csv('concrete_processed.csv', index=False)
# print("Guardado como CSV")

# 2. Guardar como Excel
# concrete_data.to_excel('concrete_processed.xlsx', index=False)
# print("Guardado como Excel")

# 3. Guardar como archivo pickle (formato de Python)
# concrete_data.to_pickle('concrete_processed.pkl')
# print("Guardado como Pickle")

print("Ejemplos de guardado comentados (descomenta para usar)")

Ejemplos de guardado comentados (descomenta para usar)

## 📚 Resumen de Funciones Principales en Pandas

### **Exploración de Datos**
- `.head()` - Ver las primeras filas
- `.tail()` - Ver las últimas filas
- `.info()` - Información sobre el dataframe
- `.describe()` - Estadísticas descriptivas
- `.shape` - Dimensiones (filas, columnas)

### **Acceso a Datos**
- `df['columna']` - Acceder a una columna (Series)
- `df[['col1', 'col2']]` - Acceder a varias columnas
- `df.iloc[posicion]` - Acceso por posición
- `df.loc[indice]` - Acceso por etiqueta del índice

### **Filtrado**
- `df[df['columna'] > valor]` - Filtrar por condición
- `df[(df['col1'] > val) & (df['col2'] < val)]` - Múltiples condiciones

### **Operaciones Estadísticas**
- `.mean()`, `.median()`, `.std()`, `.min()`, `.max()`, `.sum()`
- `.value_counts()` - Contar valores únicos
- `.groupby()` - Agrupar datos
- `.agg()` - Agregar múltiples funciones

### **Manipulación**
- `df.sort_values()` - Ordenar datos
- `df.rename()` - Renombrar columnas
- `df.isnull()` - Detectar valores faltantes
- `df.dropna()` - Eliminar valores faltantes
- `df.fillna()` - Rellenar valores faltantes

### **Exportar**
- `.to_csv()` - Guardar como CSV
- `.to_excel()` - Guardar como Excel
- `.to_pickle()` - Guardar como Pickle

## 🎯 Ejercicios Prácticos

1. **Exploración básica**: ¿Cuántas muestras tenemos en el dataset? ¿Cuántas columnas?

2. **Filtrado**: ¿Cuántas muestras tienen resistencia menor a 10 MPa?

3. **Estadísticas**: Calcula la media, mediana y desviación estándar de la columna de agua (Water (component 5)(kg in a m^3 mixture))

4. **Agrupación**: ¿Cuál es el promedio de agua por categoría de resistencia?

5. **Nueva columna**: Crea una columna que indique si la resistencia está "por encima" o "por debajo" de la media

6. **Ordenamiento**: Encuentra las 10 muestras con mayor cantidad de cemento

7. **Combinación**: Filtra las muestras con resistencia > 30 Y cemento < 250, ¿cuántas hay?